name: Create student version

on:
  workflow_dispatch:
    inputs:
      semester:
        description: 'Semester you want to generate, make sure that SEMESTER_WEEKS_XX exists' 
        default: ''
        required: true

jobs:
  create_student_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools nbformat nbgrader traitlets
      - name: Run script
        env: 
          SEMESTER_WEEKS: ${{ vars[format('SEMESTER_WEEKS_{0}', inputs.semester )] }}
        run: python utils/create_student_version.py
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: student-version
          path: release
  push_to_renku:
    needs: create_student_version
    runs-on: ubuntu-latest
    steps:
      # Download artifacts from the parent workflow
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: student-version
          path: notebooks

      - name: Display artifact content
        run: head notebooks/Inhaltsverzeichnis.ipynb
  generate_feedback_ids:
    needs: create_student_version
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Download artifacts from the parent workflow
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: student-version
          path: notebooks
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat
      - name: Run script
        env: 
          SEMESTER_WEEKS: ${{ vars[format('SEMESTER_WEEKS_{0}', inputs.semester )] }}
        run: python utils/generate_feedback_ids.py
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: feedback_json
          path: feedback_ids.json
  generate_feedback_sql:
    needs: generate_feedback_ids
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Download artifacts from the parent workflow
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: feedback_json
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat
      - name: Run script
        run: python utils/generate_sql_statement.py
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: feedback_sql
          path: feedback_ids.sql