name: Push to renku 

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The target branch"
        required: false
      release_url:
        description: "The URL of the draft GitHub release"
        required: false
      steps_to_skip:
        description: "Comma separated list of steps to skip"
        required: false
  workflow_run:
    workflows: ["Create student version"]
    types: [completed]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Download artifacts from the parent workflow
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts
          path: artifacts

      - name: Display artifact content
        run: cat artifacts/my_artifact.txt